MusixMatch url sanitize
rhnvrm/lyric-api-go pull request #5
Opened 2022-08-26 18:18 UTC by aymanbagabas

* Sanitize MusixMatch URL to match on more songs
* Fix SongLyrics out of bound error

2022-08-29 05:33 UTC, rhnvrm requested changes
LGTM, few minor suggestions

2022-08-29 05:33 UTC, rhnvrm commented on musixmatch/fetch.go
> +	log.Printf("src: %s", url)
Please remove the debug log.

2022-08-29 05:33 UTC, rhnvrm commented on musixmatch/helper.go
> +var urlRegexp = regexp.MustCompile(`[^a-zA-Z0-9 ]`)
Maybe we can format it as 
```
var (
  urlRegexp = ...
  whitespaceRegexp = ...
)

2022-08-29 16:21 UTC, aymanbagabas commented on musixmatch/helper.go
> +var urlRegexp = regexp.MustCompile(`[^a-zA-Z0-9 ]`)
done

2022-08-30 05:58 UTC, rhnvrm approved these changes

2022-08-30 05:58 UTC, merged